name: GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEAD_BRANCH: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - name: config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email noreply@github.com
      - name: fetch
        run: |
          git fetch --depth 1 origin "${HEAD_BRANCH}"
          git checkout "${HEAD_BRANCH}"
      - name: build
        run: ./build.sh
      - name: commit
        run: |
          git add -A
          git commit -m "update all in one [ci skip]" || true
      - name: push
        run: |
          git push
