name: GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEAD_BRANCH: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - id: branch
        run: |
          echo "::set-output name=name::$(echo "${HEAD_BRANCH}" | sed -e s@refs/[^/]*/@@g)"
      - name: config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email noreply@github.com
      - name: fetch
        run: |
          git fetch --depth 1 origin ${{ steps.branch.outputs.name }}
      - name: checkout
        run: |
          git checkout ${{ steps.branch.outputs.name }}
      - name: build
        run: ./build.sh
      - name: commit
        run: |
          git add -A
          git commit -m "update all in one [ci skip]" || true
      - name: push
        run: |
          git push origin HEAD
